# Puerto estándar
listener 1883
# Permitir conexiones sin usuario/password (para pruebas en la instalación)
allow_anonymous true

# Persistencia de datos (opcional)
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/data/mosquitto.log